# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cov_cal_long <- function(beta, M, YS, XS, dati, datj) {
    .Call(`_tAUC_cov_cal_long`, beta, M, YS, XS, dati, datj)
}

